### ISSUE TITLE
/odom data for ros2 branch

### ISSUE THREAD

**Issue by elinemha** [dawonn/vectornav#101]
Hi!
I have a vectornav vn-300 and use ros2 foxy for my project. I was wondering if you were planning on adding odometry data to the publisher like it is on the ros1 branch?

**Comment by dawonn** [comment]
No plans, feel free to send a pull request

**Comment by DoanNguyenTrong** [comment]
@elinemha Why don't you feed the data to ekf localization (robot_localization package) to get odom? It cannot be done?

**Comment by elinemha** [comment]
This is what I ended up doing, it works fine!
