### ISSUE TITLE
async mode not being set properly

### ISSUE THREAD

**Issue by salsicha** [dawonn/vectornav#12]
This happens when I try to run the launch file:

`roslaunch vectornav vn200.launch 
... logging to /home/lbnl/.ros/log/0893c812-97db-11e7-bce1-3c07547d5062/roslaunch-alex-mac-pro-9509.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mac-pro:39781/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /vectornav/async_output_rate: 50
 * /vectornav/async_output_type: 0
 * /vectornav/binary_data_output_port: 1
 * /vectornav/binary_gps_data_output_rate: 1
 * /vectornav/binary_imu_data_output_rate: 100
 * /vectornav/binary_ins_data_output_rate: 1
 * /vectornav/gps/frame_id: LLA
 * /vectornav/imu/frame_id: LLA
 * /vectornav/serial_baud: 115200
 * /vectornav/serial_port: /dev/ttyUSB0

NODES
  /
    vectornav (vectornav/vn200_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[vectornav-1]: started with pid [9527]
[ INFO] [1505239581.376709429]: Initializing vn200. Port:/dev/ttyUSB0 Baud:115200

[ INFO] [1505239581.524180412]: About to set SynchronizationControl
[ WARN] [1505239581.613558954]: Received invalid packet from vectornav.
[ WARN] [1505239581.655913164]: Received invalid packet from vectornav.
[ WARN] [1505239581.656498010]: Received invalid packet from vectornav.
[ WARN] [1505239581.707007988]: Received invalid packet from vectornav.
[ WARN] [1505239581.707319778]: Received invalid packet from vectornav.
[ WARN] [1505239581.758929227]: Received invalid packet from vectornav.
[ WARN] [1505239581.759502688]: Received invalid packet from vectornav.
[ WARN] [1505239581.812449440]: Received invalid packet from vectornav.
...
`

If I use a python script to set register 6 (async mode) to 0 then it starts working. Any reason why async mode isn't being set properly by the node or launch file?

**Comment by dawonn** [comment]
I no longer have the hardware, so I rather blindly accept pull requests. So if you would kindly send me a PR, I will merge a fix.
