### ISSUE TITLE
cant get INS messages

### ISSUE THREAD

**Issue by abdlrhmn58** [dawonn/vectornav#139]
iam using ubuntu 18.04 on jetson nano with ROS2 Eloquent
iam using vectornav100
when i ros2 topic echo /vectornav/raw/ins 
it gives me zeroes how to modify it to get real data?
thankyou

**Comment by dawonn** [comment]
Could be so many different things, but I would start by making sure you
have the USB port configured correctly and with proper permissions.

Try adding some breakpoints to the node or print statements and figure out
where it's broken. It's a great skill to learn and this driver is pretty
simple to learn on. ;)

Good luck!

**Comment by abdlrhmn58** [comment]
@dawonn thank you for your reply 

i make sure before executing the node to write the following command sudo chmod 666 /dev/ttyUSB0


and it works properly when i echo topics like vectornav/raw/common or /vectornav/imu

but what i need is ins when i try to echo /vectornav/raw/ins


![image](https://github.com/dawonn/vectornav/assets/114335326/ebabb15f-6362-4918-b0b1-ba10ce950077)


i tried to search in files vectornav.cc and vn_sensor_msgs.cc

it seems that there is a missing line in publishers at vn_sensor_msgs.cc for ins 

![image](https://github.com/dawonn/vectornav/assets/114335326/729cfbd2-ceca-4624-ad2f-e017a3dd20c2)


![image](https://github.com/dawonn/vectornav/assets/114335326/a34d98e0-fe41-4026-9a8f-49cffd24741c)


so what is your opinion ..

i appreciate your help

**Comment by dawonn** [comment]
Vm100 doesn't have an INS solution, it has no GNSS receiver.

**Comment by dawonn** [comment]
https://github.com/dawonn/vectornav/blob/master/src/main.cpp#L813

**Comment by abdlrhmn58** [comment]
So its my mistake 
Thanks :)
