### ISSUE TITLE
Library for vectornav 100

### ISSUE THREAD

**Issue by dahlan77** [dawonn/vectornav#14]
I clone this package and unfortunately .it doesn't support for my vectornav 100.Any solution to make this package can be used with vectrnav 100

Best Regard

Dahlan

**Comment by dawonn** [comment]
I'm actually working on vn100 and 300 right now. But it will be a week or two before I can publish a beta version for you

**Comment by dahlan77** [comment]
thank you dawonn

for your helping..its really helpfull for me  


Best regard 

Dahlan

**Comment by dawonn** [comment]
VN100 does not support GPS.

**Comment by dahlan77** [comment]
really
but in datasheet 

VectorNav | VN-100 SMD | NavtechGP 
VN100 Development Kit

there are part for gps
