### ISSUE TITLE
Binary Rate at 400 Hz possible?

### ISSUE THREAD

**Issue by athtest800** [dawonn/vectornav#27]
Is it possible to have Binary Rate Output at 400 Hz?

**Comment by shrijitsingh99** [comment]
Yes, you can get data from VectorNav at upto 800Hz.

**Comment by athtest800** [comment]
When I set it with this driver, I get error and the node terminates. Is there solution? What can I modify in order to work?

**Comment by dawonn** [comment]
You may need to reduce the number of message types being read from the vn
device, and / or increase the baud rate.
