### ISSUE TITLE
GPS & Odom Data Still Missing After Recent Fix

### ISSUE THREAD

**Issue by dlee640** [dawonn/vectornav#53]
Hello. I have VN-100 and I got this amazing repo to work on my system, except for vectornav/Odom and vectornav/GPS topics. Roslaunch runs without any error, and I can get access to other topics such as Imu, Pres, Temp...etc but NOT odom & GPS topics, as they return no new messages.

This seems like the same error shown in #26 except the 'merge' that dawonn mentioned did not seem to solve the issue as I have used the most recent commit to do this.

What were the necessary fixes to resolve the issue? I have checked all the previous issues related to this, but none of them seem to be relevant atm.

Thank you.

**Comment by bjajoh** [comment]
The VN100 is an AHRS without GNSS functionality, so you will have a hard time to get any GPS or Odom topics. ;)
