### ISSUE TITLE
can't establish connection VN-100

### ISSUE THREAD

**Issue by raess1** [dawonn/vectornav#63]
I am trying this ROS driver and can't establish connection  to the VN-100. 
Specs:
Ubuntu 18.04
/dev/ttyS6
Using UART serial2 from the Vectornav since I have a custom cable for it which I configured the same as serial1 in CC (115200baud)

I also specified the `serial_baud: 115200` and `serial_port: /dev/ttyS6` in `vn100.yaml`

Cable:
![20210522_213642](https://user-images.githubusercontent.com/6362413/119268995-ba2fab80-bbf5-11eb-9b5c-be7170c581d7.jpg)

Using `picocom -b 115200 /dev/ttyS6` I successfully see data in terminal.

https://user-images.githubusercontent.com/6362413/119269055-10045380-bbf6-11eb-842c-a05329a47707.mp4

Any advice or help would be appreciated!

Thanks in advance
/rf

**Comment by dawonn** [comment]
I did not test serial port two on any of my devices, so you might be an
uncharted waters, There's no reason why it shouldn't work however.

You may need to tweak the binary output configuration to point at the other
port:
https://github.com/dawonn/vectornav/blob/634920c046b00bd04ebdbb07ba18bc03174ed5d6/src/main.cpp#L236

**Comment by raess1** [comment]
Thanks for the prompt reply. Yeah I did a quick test setting `ASYNCMODE_PORT2` without success. 

So the serial port from vectornav should output binary? Do you have any example from CC how yours is configured over serial1 output? :) That might be helpful

Thanks 
/RF

**Comment by dawonn** [comment]
Yes the serial port should be configured as binary output by the Ros node.
This is essentially necessary to get good performance due to the amount of
data being sent. Admittedly the VN100 might be fine because you're only
reading the IMU data but the VN200 and VN300 can definitely saturate the
link.

Essentially that block of code is what does it, There's not too much to it
really. Do you even establish a connection to the device, does it tell you
the serial number and model number etc? If that doesn't work nothing else
is likely to.

You'll also probably want to remove the flags for the output groups that
don't exist on the v100.

**Comment by raess1** [comment]
Thanks. Nah it doesn't tell me anything. Not serial or device info. I sell send error image soon.

I guess I can try with the original cable to confirm it's working from that.

I be back

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by raess1** [comment]
So normal cable gives me  `Device connection established`

But also throws the error 
![12312132](https://user-images.githubusercontent.com/6362413/119272253-6200a580-bc05-11eb-98f4-fb4228348649.PNG)

**Comment by raess1** [comment]
Okej. Increasing baud to` /dev/ttyUSB0 @ 230400 Baud` solves that problem with orginal cable

**Comment by raess1** [comment]
So I got my cable working and got Device connection established and Get the following error.
![112123132](https://user-images.githubusercontent.com/6362413/119313885-59938380-bc74-11eb-868d-79fc7dd41ba0.PNG)

**Comment by raess1** [comment]
success
Changed /dev/ttyS6 @ 921600 Baud
and  `ASYNCMODE_PORT1` -> `ASYNCMODE_PORT2` 

![woop](https://user-images.githubusercontent.com/6362413/119314320-e9d1c880-bc74-11eb-98de-480189ad9d9f.PNG)

**Comment by raess1** [comment]
So after a little more testing. 
I can't access it after reboot with my cable. It works if unplug my cable and use orginal cable and open CC and then Plugin my cable again and then try the ROS driver again.

**Comment by raess1** [comment]
I made a new cable which seems to work alot better. 
![20210525_124833](https://user-images.githubusercontent.com/6362413/119495263-87ef8c80-bd62-11eb-9919-c64a4df8a0a5.jpg)

**Comment by dawonn** [comment]
That's great, happy to hear it.
