### ISSUE TITLE
 Package version ":{version}" does not follow version conventions

### ISSUE THREAD

**Issue by kriddy101** [dawonn/vectornav#76]
Error(s) in package '/home/kriddy101/catkin_ws/src/mavlink/patch/package.xml':
Package version ":{version}" does not follow version conventions

How do I solve this? It wont let me get into the package.

**Comment by dawonn** [comment]
This appears to be an issues with another package in your workspace (`mavlink`) and not with this package. 

You can move that package out of the workspace, or create a new workspace for using this package.
